//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManagerEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public string SmtpServer { get; set; }
        public string SmtpAgentSine { get; set; }
        public string SmtpAgentDutyCode { get; set; }
        public string SmtpPort { get; set; }
        public string SmtpAgentDutyParam1 { get; set; }
        public string SmtpAgentDutyParam2 { get; set; }
        public string SmtpAgentDutyParam3 { get; set; }
    }
}
