//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManagerEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerMatch
    {
        public int PlayerMatchID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public Nullable<int> MatchID { get; set; }
        public Nullable<int> TeamID { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
