//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManagerEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.PlayerMatches = new HashSet<PlayerMatch>();
        }
    
        public int PlayerID { get; set; }
        public string PlayerName { get; set; }
        public string EmailAddress { get; set; }
        public string Mobile { get; set; }
    
        public virtual ICollection<PlayerMatch> PlayerMatches { get; set; }
    }
}
