//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManagerEF.EFModel
{
    using System;
    using System.Collections.Generic;

    public partial class Match
    {
        public Match()
        {
            this.PlayerMatches = new HashSet<PlayerMatch>();
        }

        public int MatchID { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
        public Nullable<int> MatchWinner { get; set; }

        public virtual ICollection<PlayerMatch> PlayerMatches { get; set; }
    }
}
